### ISSUE TITLE
XCode 6.3

### ISSUE THREAD

**Issue by richardPFisk** [DiUS/pact-consumer-swift#1]
Has anyone got pact-consumer-swift  working with carthage using XCode 6.3?

I've tried a few different combinations of dependencies with a forked repo changing the Cartfile but without success yet.

The carthage log is complaining about the parameters of `responseString` on master where the Alamofire dependency is explicitly "master" (where Alamofire has merged its branch 'xcode-6.3').

**Comment by andrewspinks** [comment]
Have a look in the swift1.2 branch, it was working with one of the betas of xcode-6.3 (although I guess the dependencies have moved on from then). I will update that branch when I get a second to make sure it works with the latest 6.3 release.

**Comment by richardPFisk** [comment]
Thanks for the prompt update. Yes, I tried that and received the error, 'No object named "xcode-6.3" exists'" due to the Alamofire dependency no longer having the "xcode-6.3" branch they have merged into their Master branch.

**Comment by andrewspinks** [comment]
OK, gotcha. I'll have a look at it tonight and see whats happened.

**Comment by andrewspinks** [comment]
@richardPFisk I think I've fixed the swift1.2 branch. Let me know if you still have trouble. I'll look at merging these things into master, seeing as XCode 6.3 has been out for a while (I was waiting for travisci to support it, but it doesn't look like that will happen anytime soon).

**Comment by richardPFisk** [comment]
That worked like a dream :+1:.  Thanks very much. The `completionHandler:` addition is what I was missing.
