### ISSUE TITLE
Quick dependency causing conflict.

### ISSUE THREAD

**Issue by isadamascena** [DiUS/pact-consumer-swift#101]
Steps to reproduce: 
- Add the `LaunchDarkly` library with Swift Package Manager (version 5.2.0)
- Add the `pact-consumer-swift` latest. 

I get the error bellow: 
![image](https://user-images.githubusercontent.com/38086231/96516084-d96bf200-123c-11eb-9f83-aa7af4f0421f.png)

Have you folks foreseen any action/work around for that version conflict on SPM? this can be a big issue since many libraries have Quick as dependency.  

Thanks!

**Comment by surpher** [comment]
Thanks for reporting this @isadamascena!

Just to be clear, you're using SPM to handle dependencies, even `pact-consumer-swift`? 
It should be as simple as bumping up the Quick dependency version within `pact-consumer-swift` and any clean up required for Quick 3.x.x.

**Comment by andrewspinks** [comment]
I would suggest removing Quick as a dependency if it is causing an issue. It is only required to run the project tests (which we don't run by spm in the build anyway), it shouldn't be an enforced dependency on clients.

**Comment by surpher** [comment]
That would be ideal. Though it seems that SPM pulls in the dependencies per project, not per target or how Carthage does it with `Cartfile.private`. Looking into the structure, if it can be removed for distribution.

https://github.com/DiUS/pact-consumer-swift/blob/master/Package.swift
