### ISSUE TITLE
Pact tests not working with OpenCombine and Combine code

### ISSUE THREAD

**Issue by ManaliM27** [DiUS/pact-consumer-swift#104]
Hi, The Pact tests are not working with **Combine** and **OpenCombine** code
I have written code to download the data using OpenCombine (Tried the same using Combine). But the pact tests are not working with that code. I am getting Timeout error. On executing the Pact tests, code control never reaches the **tryMap** block (Code Below)

Error : "failed - test did not complete within 30.0 second timeout" 
Error persists even after increasing the timeout interval

Code : 
```swift
 var dataPublisher: AnyPublisher<URLSession.DataTaskPublisher.Output, URLSession.DataTaskPublisher.Failure>
       dataPublisher = URLSession.shared.dataTaskPublisher(for: url!)
            .eraseToAnyPublisher()
        return dataPublisher
            .tryMap { output in
                guard let httpResponse = output.response as? HTTPURLResponse else {
                    throw APIError.invalidResponse
                }
                guard (200..<300).contains(httpResponse.statusCode) else {
                    throw APIError.statusCode(httpResponse.statusCode)
                }
                return output.data
                
            }
```
                
(If I try to rewrite the code in imperative way, the tests works fine)

**Comment by surpher** [comment]
How are you subscribing to this publisher and sending a trigger to execute the network call? How are you collecting the events your `dataPublisher` is emitting?

**Comment by ManaliM27** [comment]
There was some issue in setting the tests. So closing this issue.
