### ISSUE TITLE
Cocaopods support

### ISSUE THREAD

**Issue by erikackermann** [DiUS/pact-consumer-swift#2]
Can this project include a podspec so that it can be included via Cocoapods?

**Comment by andrewspinks** [comment]
Yeah of course. I have nothing against cocoapods! Feel free to create a pull request if you would like. Otherwise I'll try and do it over the next few days...

**Comment by erikackermann** [comment]
Thanks @andrewspinks.  I'm not sure I could do much providing a pull request with this change; you (or the project owner) will need to fill out the podspec with your details and run `pod trunk push`.

**Comment by erikackermann** [comment]
@andrewspinks this should get you started: https://github.com/DiUS/pact-consumer-swift/pull/3

**Comment by andrewspinks** [comment]
@erikackermann Cheers mate. Sorry, I did start looking at this last weekend but got bogged down in carthage bugs and travisci crap. Will try and get this going for you even if I cannot fix the build.

**Comment by andrewspinks** [comment]
@erikackermann I added the podspec. See here for an example of how to use it: https://github.com/andrewspinks/PactObjectiveCExample I haven't published it on cocoapods yet, if you can let me know if it is working for you, then I'll publish it. I am probably going to switch the build of the main project to CocoaPods as well. Originally, I used carthage because the cocoapods support for swift was not that crash hot, and I liked the simplicity of carthage. However, I am finding it really hard to track down errors in dependent libraries which are occurring with carthage on travisci.

**Comment by erikackermann** [comment]
@andrewspinks thank you so much!  I will try to integrate it now and let you know how it goes

**Comment by erikackermann** [comment]
@andrewspinks I am able to get Pact integrated using Cocoapods using the steps in PactObjectiveCExample.  That part seems to be working fine.

However, I'm having trouble getting `pact-mock-service` to start with the pre-action in the test scheme.  I have set the path for `pact-mock-service` correctly (I've verified this by writing the path to a file from the pre-action script).  It seems like the mock service is killed before the unit tests actually run?  Do you have any idea about this?  thanks for you help.

**Comment by erikackermann** [comment]
I think my issue is related to the way my ruby installation is setup.  I'll get it worked out; either way, I think the cocoapods integration is working great so we can probably merge that into master on PactConsumerSwift.

**Comment by andrewspinks** [comment]
@erikackermann Maybe start off by running the mock server manually from the terminal:

```
pact-mock-service start --log "./tmp/pact.log" --pact-dir "./tmp/pacts" -p 1234
```

You just need to start it up before the test runs and manually kill it afterwards (ctrl+c). That might be useful for getting your first test working anyway. If that is working, then it is probably a path issue. XCode doesn't use the same PATH settings as your terminal, so you will probably need to set it manually in the pre-actions script for wherever your ruby manager is installing the binary. 

```
which pact-mock-service
```

Should tell you where the binary is being installed.

Another thing to note, is that (by mistake) I have made the startup and shutdown of the pact-mock-service log to `~/nohup.out` If you look in there you may find the problem (I need to make that a relative path to a temp directory or something, not the home directory).

**Comment by erikackermann** [comment]
@andrewspinks alright, thank you for your help.  Looking at the file at `~/nohup.out` I was able to get the pre-action to use the installed `pact-mock-service` (needed to add the line `source "$HOME/.rvm/scripts/rvm"` to use rvm).

I'm having issues now when trying to write a unit test.  I get an error "No such module 'PactConsumerSwift'" on the line `import PactConsumerSwift` in PactSpec.swift.

My Podfile looks like:

```
target 'PactSpecs', :exclusive => true do
  use_frameworks!
  platform :ios, '8.0'
  pod 'PactConsumerSwift', :git => 'https://github.com/DiUS/pact-consumer-swift', :branch => 'erikackermann-cocoapods'
end
```

**Comment by andrewspinks** [comment]
@erikackermann Sorry, I'm not sure. I just tried it out with a swift project and it seemed OK:
https://github.com/andrewspinks/PactSwiftExample/tree/cocoapods

**Comment by erikackermann** [comment]
@andrewspinks alright, got it all working!  Was having lots of issues with `use_frameworks!` breaking other cocoapods I'm using, but finally got it to work by only calling `use_frameworks!` on my Pact specs target.  Looking good :+1:

**Comment by erikackermann** [comment]
Thanks again for all of your help.  I made a few small changes to the podspec: https://github.com/DiUS/pact-consumer-swift/pull/4

**Comment by erikackermann** [comment]
Should I wait until another version is released w/ cocoapods support to close this issue?

**Comment by andrewspinks** [comment]
Yeah, I'll close it when I've tagged and published to cocoapods. Hopefully I'll get to it today.

**Comment by andrewspinks** [comment]
Published on cocoapods.
