### ISSUE TITLE
extend run to include timeout

### ISSUE THREAD

**Issue by lutzj82** [DiUS/pact-consumer-swift#22]
I am running **UI tests** that utilize the mock services, but in a couple of cases the tests take longer than the default timeout for Nimble. Currently, I am having to set

```
Nimble.AsyncDefaults.Timeout = 30
```

but I'd prefer to either pass in a timeout value to **run**, or do the assert myself for testComplete
Thoughts?

Thanks

**Comment by andrewspinks** [comment]
@lutzj82 I think adding timeout value to the run method might work. I'll take a look at that when I get a sec.

**Comment by andrewspinks** [comment]
Hey @lutzj82 I have pushed a swift-2.3 branch with allows you to specify a timeout like this:

```
     animalMockService!.run(timeout: 30) { (testComplete) -> Void in
          animalServiceClient!.getAlligators( { (alligators) in
              expect(alligators[0].name).to(equal("Mary"))
              testComplete()
            }, failure: { (error) in
              testComplete()
          })
        }
```

I also retrofitted the path matcher change into this branch.
Let me know what you think.

**Comment by garie** [comment]
Am I reading it right that you defaulted the timeout to 1 second (PactConsumerSwift/MockService.swift:55)? If that is the case, that would cause every single one of our tests to start failing unless we added the timeout argument. I think 30 seconds is a much more reasonable default.

**Comment by andrewspinks** [comment]
@garie Apologies, it appears that I may have done that, my bad. A pull request would be welcome!

**Comment by garie** [comment]
PR #23 is open.
