### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by poksi592** [DiUS/pact-consumer-swift#28]
Hi, 

It seems like `testItSaysHello()` fails for me on timeout. Actually, all the methods do. Do you have any idea what could be the problem here? I installed everything needed, at least I believe so.

Thanks!

**Comment by andrewspinks** [comment]
@poksi592 If your test execution takes a long time, then yes, it may timeout. You can increase the timeout like this:
```
animalMockService!.run(timeout: 60) { (testComplete) -> Void in
      animalServiceClient!.getAlligator { (alligator) in
        expect(alligator.name).to(equal("Mary"))
        testComplete()
      }
    }
```
Also ensure that you are calling the `testComplete()` callback from the mock service.  What test framework are you using? If you can provide a sample of the test you have written, that will help in debugging the problem.

**Comment by poksi592** [comment]
@andrewspinks For whatever reason, the service wasn't started from Pre-build script...
When I started it manually, it worked. :)
Thanks!

**Comment by ghost** [comment]
@poksi592 A helpful command for your Scheme's Test `Pre-actions` and `Post-actions` that will help you debug any issues with running and stopping pact server on every test run:
```
exec > ${PROJECT_DIR}/pre-build.log 2>&1
PATH=/absolute/path/to/your/.rvm/rubies/ruby-2.3.1/bin:$PATH
"$SRCROOT"/scripts/start_server.sh 
```
