### ISSUE TITLE
Only for Tests?

### ISSUE THREAD

**Issue by poksi592** [DiUS/pact-consumer-swift#29]
Hi,

I tried to setup using this framework in the main bundle as well. The purpose is to establish the possibility of using same mocks also in the main bundle in cases some of the API's were not implemented yet, but the app still needs to work, although only with stubbed responses.
Of course, I saw the `MockService` importing Nimble and rest of the frameworks that rely on XCTest. Are you considering changing this and opening functionality to the main bundle as well?

**Comment by andrewspinks** [comment]
@poksi592 There is nothing on the roadmap to support this at the moment from this library. However, there is this stub server which you might be able to use in the same way:  https://github.com/uglyog/pact-stub-server (or a dockerised version: https://github.com/pact-foundation/pact-stub-server ) I haven't tried it yet though.
