### ISSUE TITLE
Matcher.eachLike(_:min) not generating examples in Pact file

### ISSUE THREAD

**Issue by surpher** [DiUS/pact-consumer-swift#35]
### New Issue Checklist
- [x] Updated `pact-consumer-swift` to latest version
- [x] Searched for existing GitHub issues

### Issue description
When writing Pact tests with `Matcher.eachLike(_ value: Any, min: Int)` and using 0 for `min`,
the generated Pact file does not include the provided example value.

*Given Pact test:*
```
myProvider!
.given("some values")
.uponReceiving("a request to get a list of values")
.withRequest(method: .GET, path: "/some/endpoint")
.willRespondWith(status: 200,  
                 body: ["someArray": Matcher.eachLike(["date": Matcher.term(matcher: "\\d{4}-\\d{2}-\\d{2}", generate: "2018-04-12"), 
                                                       "description": Matcher.somethingLike("Some description")], min: 0))
```

*In Pact file:*
```
{
      "description": "a request to get a list of values",
      "providerState": "some values",
      "request": {
        "method": "get",
        "path": "/some/endpoint"
      },
      "response": {
        "status": 200,
        "headers": {
        },
        "body": {
          "someArray": [
            {

            }
          ]
        },
        "matchingRules": {
          "$.body.someArray": {
            "min": 0
          },
          "$.body.someArray[*].*": {
            "match": "type"
          },
          "$.body.transactions[*].description": {
            "match": "type"
          },
          "$.body.transactions[*].date": {
            "match": "regex",
            "regex": "\\d{4}-\\d{2}-\\d{2}"
          }
        }
      }
    }
```

### Expected behaviour
Pact file should include the provided example `description` and `date`:
```
...
        "body": {
          "someArray": [
            {
              "description": "Some description",
              "date": "2018-04-04",
            }
          ]
        }
...
```

### Improvement
```
eachLike(_ value: Any, min: Int = default, examples: Int = default) -> [String : Any]
``` 
Providing *2* for examples value would *generate 2 entries* in the Pact file.
```
...
        "body": {
          "someArray": [
            {
              "description": "Some description",
              "date": "2018-04-04",
            },
            {
              "description": "lasjkdhfclakushdcfmahsdlfchm",
              "date": "8731-49-62",
            }
          ]
        },
...
```

**Comment by bethesque** [comment]
You should not be able to specify 0 as a min. It should be at least 1. From the pact docs:

> # Why is there no support for specifying optional attributes?

> Firstly, it is assumed that you have control over the provider's data (and consumer's data) when doing the verification tests. If you don't, then maybe Pact is not the best tool for your situation.

> Secondly, if Pact supports making an assertion that element $.body.name may be present in a response, then you write consumer code that can handle an optional $.body.name, but in fact, the provider gives $.body.firstname, no test will ever fail to tell you that you've made an incorrect assumption. Remember that a provider may return extra data without failing the contract, but it must provide at minimum the data you expect.

> The same goes for specifying "SOME_VALUE or null". If all your provider verification test data returned nulls for this key, you might think that you had validated the "SOME_VALUE", but in fact, you never had. You could get a completely different "SOME_VALUE" for this key in production, which may then cause issues.

> The same goes for specifying an array with length 0 or more. If all your provider verification data returned 0 length arrays, all your verification tests would pass without you ever having validated the contents of the array. This is why you can only specify an array with minimum length 1 OR a zero length array.

> Remember that unlike a schema, which describes all possible states of a document, Pact is "contract by examples". If you need to assert that multiple states are possible, then you need to provide an example for each of those states. Consider if it's really important to you before you do add a Pact test for each and every state however. Remember that each interaction comes with a "cost" of maintenance and execution time, and you need to consider if it is worth the cost in your particular situation.

https://docs.pact.io/faq#why-is-there-no-support-for-specifying-optional-attributes

**Comment by bethesque** [comment]
@MarkoJustinek ideally, the Swift DSL should raise an error if a user tries to enter a min value of 0.
