### ISSUE TITLE
Pre/post script with non-zero exit does not fail build

### ISSUE THREAD

**Issue by surpher** [DiUS/pact-consumer-swift#39]
### Setup
Running pact tests from an iOS build. 
Using _pre-actions_ and _post-actions_ of the scheme in the Xcode project to start/stop the pact mock service and then upload to the Pact broker.

**pre-actions**
```
"${PACT_BIN}/pact-mock-service" start --pact-specification-version 2.0.0 --log "${SRCROOT}/tmp/pact.log" --pact-dir "${SRCROOT}/tmp/pacts" -p 1234
```

**post-actions**
```
"${PACT_BIN}/pact-mock-service" stop
"${PACT_BIN}/pact-broker" publish "${SRCROOT}/tmp/pacts" --consumer-app-version=1.0.1 --tag master
```

### Expected result:
Non-zero exit of these scripts should fail the CI.

### Actual result:
Non-zero exit codes from pre/post test scripts don't result in the actual build being marked as an error or failure by Xcode, so it won't actually fail CI.

**Comment by sgleadow** [comment]
Thanks for that. Just for context for the scripts above, I obviously set up the PACT_BIN and then the pact broker credentials environment variables separately for these scripts to work as well, that's just the minimum context to explain the issue.

eg. even if you just put `exit 1` in those scripts, it doesn't fail

**Comment by surpher** [comment]
After some investigation Xcode's scheme scripts indeed do not honour non-zero exit codes.

I would suggest running `pact-broker` in a seperate CI step rather than in a Schemes' Test _post-actions_ script.
