### ISSUE TITLE
Update for Swift 4.2

### ISSUE THREAD

**Issue by cassandrabailey293** [DiUS/pact-consumer-swift#41]
Hi, I was wondering if there was any plan to update this repo to Swift 4.2 / XCode 10. 

I am using this library in my project, which I tried to upgrade to Swift 4.2 / XCode 10. I am getting an error in the Pact Consumer Swift module saying "No such module BrightFutures". I think this is due to BrightFutures having upgraded to 4.2 but this repo has not.

**Comment by andrewspinks** [comment]
Hi @cassandrabailey293 thanks for letting us know. Yes, it is supported, so we will upgrade as soon as I get a spare moment. PR's welcome if you want to help speed the process up!

**Comment by cassandrabailey293** [comment]
Okay, I will give it a shot!

**Comment by cassandrabailey293** [comment]
Hi @andrewspinks , I tried to upgrade it myself but I ran into the same issue - No such module found, which kept appearing on different import statements for 4 or 5 different modules. I tried to figure it out myself but I'm having some trouble. Perhaps you will have better luck than I. :)

**Comment by andrewspinks** [comment]
@cassandrabailey293 Thanks for giving it a go. I'll try and take a look today.

**Comment by andrewspinks** [comment]
@cassandrabailey293 We've released a new version with updated dependencies.

**Comment by andrewspinks** [comment]
Closing issue. If you still experience problems, we can re-open it.
