### ISSUE TITLE
Won't compile with Xcode 10.2

### ISSUE THREAD

**Issue by georgescumihai** [DiUS/pact-consumer-swift#45]
Because the versions for Nimble and Quick do not compile with Xcode 10.2, also pact doesn't compile with Xcode 10.2.
I created a PR to fix that #44

**Comment by andrewspinks** [comment]
@georgescumihai Thank you very much! I'll try and get this merged asap.

**Comment by andrewspinks** [comment]
@georgescumihai Version 0.5.4 published with your change. Thanks!
