### ISSUE TITLE
Remove unnecessary dependencies

### ISSUE THREAD

**Issue by andrewspinks** [DiUS/pact-consumer-swift#48]
Every new xcode and swift version breaks due to downstream dependencies. Reducing number of dependencies will reduce unnecessary breakages and reduce maintenance work.

Deps:

- [ ] BrightFutures
- [x] Alamofire
- [ ] Nimble (would probably need to duplicate nimbles' xcode reporting functions)

**Comment by surpher** [comment]
I've split this issue into other issues that focus on removing dependencies separately.
This issue can be closed (when open PRs are closed)
