### ISSUE TITLE
Error when using somethingLike in provider response

### ISSUE THREAD

**Issue by erikackermann** [DiUS/pact-consumer-swift#5]
I'm trying to use the `somethingLike` matcher in provider response.  Doing something like the following:

``` swift
func testItSaysHello() {
    var hello = "not Goodbye"
    helloProvider!.uponReceiving("a request for hello")
                  .withRequest(method:.GET, path: "/sayHello")
                  .willRespondWith(status: 200, 
                      headers: ["Content-Type": "application/json"], 
                      body: [
                          "id": Matcher.somethingLike(NSString),
                          "name": Matcher.somethingLike(NSString)
                      ]
                  )

    //Run the tests
    helloProvider!.run{ (testComplete) -> Void in
      self.helloClient!.sayHello { (response) in
        XCTAssertNonNil(response["id"])
        XCTAssertNonNil(response["name"])
        testComplete()
      }
    }

    waitForExpectationsWithTimeout(10) { (error) in }
}
```

When I do this, I get a crash with:

`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid type in JSON write (NSString)'`

(crash is on L128 in ParameterEncoding.swift in Alamofire)

Is this not the correct way to use the somethingLike matcher?  How can I create a pact that just verifies the existence (and type) of a few fields in a response?

**Comment by andrewspinks** [comment]
Hmmm, I thought I had an example of this around, but I can't find one.  Basically, you put the value that you want in the the somethingLike and the type will be inferred. e.g.

```
Matcher.somethingLike("12343131")
```

You can then assert on that value in your test to verify that your parsing code is correct.

```
XCTAssertEqualObjects(response["id"], "12343131")
```

NB: this will only work if you are using ruby on the server side.

**Comment by andrewspinks** [comment]
@erikackermann I'll add an example to the tests when I get a moment.

**Comment by erikackermann** [comment]
@andrewspinks thank you.  Makes sense
