### ISSUE TITLE
Won't compile under Xcode 7 with iOS 8 deployment target

### ISSUE THREAD

**Issue by erikackermann** [DiUS/pact-consumer-swift#6]
Repro steps:
- Integrate PactConsumerSwift into project with iOS 8 set as deployment target
- Build and run

Result:
- Numerous swift language errors.  Example from Interaction.swift:
  `'#' has been removed from Swift; double up 'method method' to make the argument label the same as the parameter name`
- Similar errors in AlamoFire and BrightFutures dependencies

Expected Result:
- Compiles with Xcode 7 / Swift 2 compiler without errors

**Comment by erikackermann** [comment]
Started to get this working here: https://github.com/erikackermann/pact-consumer-swift/tree/xcode-7

**Comment by andrewspinks** [comment]
@erikackermann I've had a look at this tonight, but haven't quite got it finished yet. There are some API  changes in Alamofire that I am still migrating, and I need to make sure the tests still work.

**Comment by andrewspinks** [comment]
@erikackermann I think I have pretty much got it working, although I can't get the tests to pass on the command line for some reason (they seem to work in XCode). Check out the swift 2 branch and let me know how you go: https://github.com/DiUS/pact-consumer-swift/tree/swift-2

**Comment by erikackermann** [comment]
Thanks @andrewspinks.  Taking a look now.

On Thu, Sep 24, 2015 at 6:53 AM, andrewspinks notifications@github.com
wrote:

> @erikackermann https://github.com/erikackermann I think I have pretty
> much got it working, although I can't get the tests to pass on the command
> line for some reason (they seem to work in XCode). Check out the swift 2
> branch and let me know how you go:
> https://github.com/DiUS/pact-consumer-swift/tree/swift-2
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DiUS/pact-consumer-swift/issues/6#issuecomment-142891308
> .

## 

Erik Ackermann

Mobile Development

(212) 951-0496

LinkedIn http://www.linkedin.com/in/erikackermann

176 Grand Street, 3rd Floor - New York, NY 10013

**Comment by erikackermann** [comment]
@andrewspinks sorry for the delay getting back to you.  This appears to be working (the `swift-2` branch).  I can compile this against the iOS 8 SDK.

**Comment by erikackermann** [comment]
@andrewspinks to get the build passing on Travis, I think you need to add `osx_image: xcode7` to the .travis.yml file
