### ISSUE TITLE
Update BrightFutures to a version that supports swift 5.0

### ISSUE THREAD

**Issue by GeorgeIvanov** [DiUS/pact-consumer-swift#75]
Hey, can you please update the BrightFutures dependency to a version that supports version 5? Because right now BrightFutures and Result are written in swift 4.2, thanks.

**Comment by surpher** [comment]
Thanks for the nudge. 

[PR](https://github.com/DiUS/pact-consumer-swift/pull/76) has been created. Now just waiting for a review and I can release the new minor version.

**Comment by andrewspinks** [comment]
@GeorgeIvanov sorry for the delay, but I only just managed to release this properly as v0.7.0.
