### ISSUE TITLE
Brightfutures crashes on Xcode 11.2.1, Swift 5.1, iOS 13.2 - EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by david-tigerspike** [DiUS/pact-consumer-swift#79]
Hello, 

Currently we are trying to get Pact.IO running for our iOS app. However we are unable to execute a MockService.run() without it crashing. 

The application keeps throwing a "Thread 1: EXC_BAD_ACCESS (code=2, address=0x1)"

`#2	0x0000000108391853 in AsyncType<>.onSuccess(_:callback:) at /$PROJECT/SourcePackages/checkouts/BrightFutures/Sources/BrightFutures/AsyncType+ResultType.swift:33`

It seems that the problem is with Brightfutures. We could provide with a short Demo Project in order to reproduce the issue. 

Thanks

**Comment by andrewspinks** [comment]
@david-tigerspike If you can provide replication steps, or even better, a demo project, that will greatly assist.

**Comment by david-tigerspike** [comment]
@andrewspinks Thanks for your quick response. 

Here you'd find attached a Demo Project. Just simply run the tests for it and it should fail. 

Just to confirm. Our current set up is: 

Xcode version: 11.2.1 (11B500)
Swift: 5.1
iOS: 13.2

[PactTest.zip](https://github.com/DiUS/pact-consumer-swift/files/3909352/PactTest.zip)


Thanks again for your help

**Comment by surpher** [comment]
Hi @david-tigerspike I’ve tested this and it seems to be a SPM bug in Xcode 11.2. It works fine with Carthage. I’m about to confirm if it works or not with Xcode 11.3. 

Is there a hard requirement for you to use 11.2?

**Edit:**
I managed to run your `PactTest.zip` project with Xcode 11.3 beta, yet I needed to explicitly add `CwlPreconditionTesting 2.0.0` package to the SPM (unfortunately that is pulled in by _Nimble_). SPM doesn't seem to be super stable and we had issues with it on other projects as well. Can you get around this issue by using different implementation method (Carthage or bumping up the Xcode version)?

**Comment by david-tigerspike** [comment]
Thanks for your reply and time @surpher 

Sadly we are unable to use Carthage and we are waiting for XCode 11.3 to get out of the BETA. For now we will do the imports manually in order to get it working. We will keep an eye out for the new XCode version. 

Thanks again

**Comment by surpher** [comment]
No problem. Xcode 11.3 is out of beta since yesterday! You're in luck ;)
