### ISSUE TITLE
Support for writing pacts in swift with cocoapods

### ISSUE THREAD

**Issue by kumarSC** [DiUS/pact-consumer-swift#9]
Hey @andrewspinks , I am trying to integrate this framework with my iOS project written in Swift 2 with Cocoapods as dependency manager.Since I wanted to avoid adding another DM with Carthage, I tried to use Cocoapods support instructions and then write tests using Swift? Not sure if it's not legitimate here? Also if I add this to my podfile  , pod 'PactConsumerSwift' , it grabs older PactConsumerSwift (0.1.3) which has downstream dependency on older versions of Alamofire and BrightFutures( which is conflicting with my existing dependencies).However, I saw commits where you have updated their versions on master with framework version bumped to 0.1.5, https://github.com/DiUS/pact-consumer-swift/commit/7971431daa5e38b19806a3831e975bda78ba4e1b .
Any idea why I am not able to fetch latest framework version with cocoapods on master?

**Comment by andrewspinks** [comment]
@kumarSC I think there was an error when I tried to publish to cocoapods and I didn't get around to fixing it. You should be able to use the latest version by specifying the git tag:

pod 'PactConsumerSwift', :git => 'https://github.com/DiUS/pact-consumer-swift.git', :tag => '0.1.5'

I'll publish the new version to cocoapods.

**Comment by andrewspinks** [comment]
@kumarSC Cocoapods is now up to date.

**Comment by kumarSC** [comment]
Hey @andrewspinks , I was trying to update pact-consumer-swift with cocoapods and seems to be broken again, I am getting the following error on running pod install.

`Pre-downloading:`PactConsumerSwift`from`https://github.com/DiUS/pact-consumer-swift.git`, tag `0.1.5`

`[!] Error installing PactConsumerSwift
[!] /usr/bin/git clone https://github.com/DiUS/pact-consumer-swift.git /var/folders/26/5pwkkbhd24z6gwjzm3bcf_r08rpvk_/T/d20160829-41092-34674d --single-branch --depth 1 --branch 0.1.5

Cloning into '/var/folders/26/5pwkkbhd24z6gwjzm3bcf_r08rpvk_/T/d20160829-41092-34674d'...
warning: Could not find remote branch 0.1.5 to clone.
fatal: Remote branch 0.1.5 not found in upstream origin`

Could you please look into it.We have started some contract testing work for our iOS project and need to keep going with latest changes.

**Comment by andrewspinks** [comment]
@kumarSC That seems weird, the tag hasn't been changed. I believe the tag was called 'v0.1.5' - maybe that has something to do with it. I published a new version (0.3) to cocoapods last week, so maybe you could try it without any tag?
