### ISSUE TITLE
pact.io framework is not building with Xcode 11.4

### ISSUE THREAD

**Issue by mmysliwiec** [DiUS/pact-consumer-swift#91]
Both Carthage and Xcode (11.4) can't build the current 0.8.0 version of pact-consumer-swift framework. I can see linker issues:

    ld: warning: Could not find or use auto-linked library 'XCTestSwiftSupport'
    ld: warning: Could not find or use auto-linked framework 'XCTest'

**Comment by surpher** [comment]
I was looking into this last week already but have had little luck so far. From what I have found from across the internet is this looks like an SPM issue. 

I'll keep looking for a solution though.

**Comment by coloverde** [comment]
I just discovered the exact same issue. It also occurs with previous versions of pact-consumer-swift.

**Comment by marc-48k** [comment]
The fix is to set `ENABLE_TESTING_SEARCH_PATHS` to true.

**Comment by surpher** [comment]
Thanks @marc-48k ! Seems like it could be a winner here. 
I'm just looking into the "supported" environments matrix to see if it will stick 👍

**Comment by mmysliwiec** [comment]
@andrewspinks When we can expect a release with this fix? It's kind of important now :-).

**Comment by andrewspinks** [comment]
@mmysliwiec 0.8.1 has now been released.
